@cppcheck^
    --enable=all^
    --inconclusive^
    --language=c++^
    --quiet^
    --suppress=unusedFunction^
    --suppress=missingIncludeSystem^
    --inline-suppr^
    -Ileviathan\include^
    -ileviathan\vendor^
    leviathan^
    sandbox